# permissions for end users to edit featureflags.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: featureflag-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operators
    app.kubernetes.io/part-of: operators
    app.kubernetes.io/managed-by: kustomize
  name: featureflag-editor-role
rules:
- apiGroups:
  - deployment.github.com
  resources:
  - featureflags
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployment.github.com
  resources:
  - featureflags/status
  verbs:
  - get
