apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: operators.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: FeatureFlag is the Schema for the featureflags API
      displayName: Feature Flag
      kind: FeatureFlag
      name: featureflags.deployment.github.com
      version: v1alpha1
  description: an operator to manage feature flag resources in kubernetes environment
  displayName: feature-flag-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - feature
  - flag
  - cloud
  - native
  links:
  - name: Operators
    url: https://operators.domain
  maturity: alpha
  provider:
    name: ff-operator
  version: 0.0.0
